# @package _global_

# NOTE: This custom launcher (separate from the built-in 'hydra/launcher' node) is meant to override global options
# that depend on the hardware resources available and for which the default options are for local runs
# (e.g. GPU devices, number of dataloader workers, progress bar display, etc.)

defaults:
  - override /hydra/launcher: beluga

trainer:
  devices: 1
  enable_progress_bar: False

datamodule:
  num_workers: 9
