defaults:
  - nnunet

net:
  in_channels: 1
  num_classes: 5
  patch_size: [96, 80, 20]
  kernels: [[3, 3, 1], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  strides: [[1, 1, 1], [2, 2, 1], [2, 2, 2], [2, 2, 2], [2, 2, 1]]

loss:
  soft_dice_kwargs: { "batch_dice": False, "smooth": 1e-05, "do_bg": False }
